spring.datasource.username: root
spring:
  datasource:
    password: Satara@123
    url: jdbc:mysql://localhost:3306/restapi
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8181